sources:
  production_by_state:
    args:
      sql_expr: SELECT date,api,volume_oil_formation_bbls,volume_gas_formation_mcf,volume_water_formation_bbls FROM {{schema}}.production_all
        WHERE state='{{state}}'
      sql_kwargs:
        parse_dates:
        - date
      uri: postgresql://{{bazean_postgres_username}}:{{bazean_postgres_password}}@{{subdomain}}.bazean.com:5432/db
    description: 'Production History For All Wells in {{state}}'
    driver: intake_sql.intake_sql.SQLSource
    metadata: {}
    parameters:
      bazean_postgres_username:
        description: "PostgresSQL username for accessing Bazean Database"
        type: str
        default: "env(BAZEAN_POSTGRES_USERNAME)"
      bazean_postgres_password:
        description: "PostgresSQL password for accessing Bazean Database"
        type: str
        default: "env(BAZEAN_POSTGRES_PASSWORD)"
      subdomain:
        description: "Bazean PostgresSQL subdomain name"
        type: str
        default: "premium"
      schema:
        description: "Bazean PostgresSQL database schema"
        type: str
        default: "public"
      state:
        description: "State to query production"
        type: str
        allowed: ["ND", "NM", "TX"]
  production_by_state_csv:
    args:
      urlpath: '{{ CATALOG_DIR }}/{{state}}_production.csv' 
      csv_kwargs:
        parse_dates:
        - 1 
    description: 'Production History For All Wells in {{state}}'
    driver: intake.source.csv.CSVSource
    metadata: {}
    parameters:
      state:
        description: "State to query production"
        type: str
        allowed: ["ND", "NM", "TX"]